### PR TITLE
Add Automate Datastore that contains methods for Openstack floating I…

### LINKED ISSUE #26: Automate script to create & attach floating IP addresses to Openstack instances
Currently the MIQ REST API does not provide a collection with actions to create floating IP addresses and attach the IP to instances.

In order to provide networking capabilities #16 we need to leverage MIQ automate feature. We need to create an automate script (Ruby language) to create/attach IP to instances. Which can be called via the REST API automation_requests collection.

TBD
* Parameter input

### PR DESCRIPTION
**Pull request by smatula**
Add Automate Data store that contains methods for Openstack floating IP processing.
Closes #26 and #27

### CODE REVIEW

**Comment by tvieira** [comment]
How do I test it?

**Comment by smatula** [comment]
To test Methods:

add_floating_ip - will create floating ip. Input tenant id and ext network id. 
allocate_floating_ip - will create and attach floating ip to vm/instace. Input vm, Optional network. 
release_floating_ip - will detach and remove a floating ip. Input Ip name or id.
retire_floating_ip - will detach and delete all floating ips from vm instance. Input of vm.
                             vm can be given by name or id.

Import to Cloudforms or ManageIQ.

    Make sure 'Git Repositories Owner' is on in your CloudForms/ManageIQ system.
    Performed from Configuration.  The Configuration located in the drop down in the upper right hand corner.
    Settings->Zones

    Perform Import
    Automation->Automate->Import/Export
    Import get_floating_ip from Git

    Once imported you may run it through the rest api as follows:

    A. Update the input json payload file with correct values for method.
            Example content:
{
  "uri_parts": {
    "namespace": "CF_MIQ_CLI/General",
    "class": "Methods",
    "instance": "get_floating_ip"
  },
  "parameters": {
    "cloud_network_id": 2,
    "cloud_tenant_id": 1
  },
  "requester": {
    "auto_approve": true
  }
}
 
    B. Execute:

    http --verify=no -a : POST https://<manageIQ/cloudforms>:8443/api/automation_requests @<payload_file.json>

    C. Keep checking for Command to finish. Returned request_state equals 'finished'. <id> is the id returned for command executed in B.

    http --verify=no -a : https://<manageIQ/cloudform>:8443/api/automation_requests/

    D. Get results from returned data. Once finished. Options will be updated with the return data.

**Review by ryankwilliams — APPROVED** [review]
LGTM

I may have more questions once I start testing out the automate scripts. It would be nice to have a README file that @vi-patel mentioned explaining the steps on how you can use these scripts.

**Review by tvieira — APPROVED** [review]
LGTM

**Comment by tvieira** [comment]
Thanks for explaining @smatula !

**Review by vi-patel — COMMENTED** [review]
looks good to me.

**Pull request merged**
